from pathlib import Path

path = Path('test/features/organization_management_test.dart')
text = path.read_text()
old = """    return updatedTeacherAssignment!;\n  }\n\n  @override\n  Future<List<OrganizationStudentRecord>> listStudents({\n"""
new = """    return updatedTeacherAssignment!;\n  }\n\n  @override\n  Future<OrganizationTeachingHandoffPlan> previewStudentTeacherHandoff({\n    required String organizationId,\n    required String assignmentId,\n    required String replacementMembershipId,\n  }) async {\n    final assignment = studentTeacherAssignments.firstWhere(\n      (item) => item.assignmentId == assignmentId,\n    );\n    final replacement = setupOptions.teachers.firstWhere(\n      (item) => item.membershipId == replacementMembershipId,\n    );\n    return OrganizationTeachingHandoffPlan(\n      organizationId: organizationId,\n      businessDate: DateTime(2026, 9, 4),\n      studentSubjectProfileId: assignment.studentSubjectProfileId,\n      studentId: assignment.studentId,\n      studentName: assignment.studentName,\n      organizationSubjectId: assignment.organizationSubjectId,\n      subjectName: assignment.subjectName,\n      subjectCode: assignment.subjectCode,\n      assignmentId: assignment.assignmentId,\n      assignmentRole: assignment.assignmentRole,\n      assignmentVersion: assignment.version,\n      sourceMembershipId: assignment.membershipId,\n      sourceTeacherName: assignment.teacherName,\n      replacementMembershipId: replacement.membershipId,\n      replacementTeacherName: replacement.displayName,\n      replacementScopeId: 'scope-preview-${replacement.membershipId}',\n      affectedCases: const <OrganizationTeachingHandoffCase>[],\n      affectedActions: const <OrganizationTeachingHandoffAction>[],\n    );\n  }\n\n  @override\n  Future<OrganizationStudentTeacherAssignmentTransferResult>\n  commitStudentTeacherHandoff({\n    required String operationId,\n    required OrganizationTeachingHandoffPlan plan,\n  }) {\n    return transferStudentTeacherAssignment(\n      operationId: operationId,\n      organizationId: plan.organizationId,\n      assignmentId: plan.assignmentId,\n      expectedAssignmentVersion: plan.assignmentVersion,\n      replacementMembershipId: plan.replacementMembershipId,\n    );\n  }\n\n  @override\n  Future<List<OrganizationStudentRecord>> listStudents({\n"""
count = text.count(old)
if count != 1:
    raise SystemExit(f'fake handoff methods: expected exactly one match, found {count}')
path.write_text(text.replace(old, new, 1))
